### ISSUE TITLE
Misleading errors in queries with subselects

### ISSUE THREAD

**Issue by jasonmp85** [citusdata/pg_shard#14]
_From @samay-sharma on November 21, 2014 14:56_

I am reporting this mainly because of the query it sends to the worker node. I don't think this is a high priority but we should show a clearer error message on the master.

Steps to reproduce:
```sql
SELECT count(*) FROM lineitem WHERE l_orderkey = (SELECT min(l_orderkey) FROM lineitem);
# WARNING:  Bad result from ip-10-102-169-241.ec2.internal:5432
# DETAIL:  Remote message: there is no parameter $0
# WARNING:  Bad result from ip-10-181-241-37.ec2.internal:5432
# DETAIL:  Remote message: there is no parameter $0
# ERROR:  could not receive query results
```

Worker node log:
```sql
# LOG:  statement: SELECT l_orderkey FROM ONLY lineitem_32 WHERE (l_orderkey = $0)
# ERROR:  there is no parameter $0 at character 61
# STATEMENT:  SELECT l_orderkey FROM ONLY lineitem_32 WHERE (l_orderkey = $0)
```

The error message while having such a `WHERE` condition in an `UPDATE` statement is also misleading.
```sql
# Showing min value
SELECT min(l_orderkey) FROM lineitem;
#  min 
# -----
#   1
# (1 row)

# This works as expected
UPDATE lineitem SET l_linenumber = 2 WHERE l_orderkey = 1;
# UPDATE 1

# This statement should touch only one shard, so the error message is a bit misleading.
UPDATE lineitem SET l_linenumber = 2 WHERE l_orderkey = (SELECT min(l_orderkey) FROM lineitem);
# ERROR:  cannot modify multiple shards during a single query
```

**Comment by onderkalaci** [comment]
Hey @jasonmp85 ,

This issue is somehow different than how it was opened.

* In summary, pg_shard is able to identify only a subset of subqueries. For the queries that pg_shard cannot identify the subselects, it sends them to worker nodes as ordinary queries and thus queries fail.

* My observation is based on ErrorIfQueryNotSupported function. In that function, to find the subqueries we only check rangeTableEntry->rtekind variables (though the check is implicit).
However, when I looked at RTEKind enum, I see the following (./src/include/nodes/parsenodes.h@714  - postgresql-9.4.0):

	RTE_SUBQUERY,				/* subquery in FROM */  

* This means that, RTE_SUBQUERY is only adequate for checking subqueries in FROM clause. This observation is also compatiable with the examples on the issue description.

* The other types of subqueries (ie: subquery in where statement) seems to be checked with queryTree->hasSubLinks variable. I wrote "seems to be", because I could not find any documantation that
clearly states this.

* I traced and debugged the code and, in summary, figured out that if there exists any subqueries in SELECT or WHERE clauses, queryTree->hasSubLinks is set to true.
Similary, if there exists any subqueries in FROM clause, we only get RTE_SUBQUERY in the corresponding range table entry. These happen on query rewrite phase.

* I executed different tests and chatted with @metdos about this issue. 
Both my tests and the chat with Metin directed me to check subqueries with both of rangeTableEntry(ies)->rtekind and queryTree->hasSubLinks variables. In citus, we do a similar check too.

* Apart from that, we definitely need to improve the error messages from "unsupported range table type:" to something like "subqueries are not supported".

If this solution makes sense, I may start implementing it.

**Comment by jasonmp85** [comment]
If I'm reading your description correctly it sounds like we have several cases:

  * Range table subqueries currently produce a message about unsupported range table type. This message should be made more clear
  * The `Query` struct's `hasSubLinks` field can be used to detect subqueries elsewhere in a query (such as in `WHERE`). Right now the behavior is as follows, but we want to change all cases to error:
    * `SELECT` statements see no qual to restrict the query to a particular shard, so send it to all shards
    * Modifications see no qual and fail because they think multiple shards are involved

I think we should see whether this functionality overlaps with detection of [common table expressions](http://www.postgresql.org/docs/9.4/static/queries-with.html) and make sure they're handled gracefully as well if so. What you've said here makes sense to me so it might be time to move this discussion to a pull request with some code. Run this by @ozgune and I'll ping @sumedhpathak for a quick sanity check but everything you've said makes sense to me.
