### ISSUE TITLE
Improve metadata synchronization

### ISSUE THREAD

**Issue by jasonmp85** [citusdata/pg_shard#26]
Give Citus users a general UDF to sync pg_shard metadata with Citus catalogs.

**Comment by ozgune** [comment]
We could even break up this issue into two components.

1. Generic UDF that syncs metadata from pg_shard to CitusDB: When a user creates a new pg_shard table, they can then call this UDF to sync table metadata. This enables users to get quickly started with CitusDB.
2. Continuous metadata sync from pg_shard to CitusDB: In production, users will likely need their pg_shard metadata synced to CitusDB in real-time. Otherwise, Citus' Select queries may return stale results. One way to achieve real-time syncs is through triggers on metadata tables.
